site:
  name: 'Sedot WC Sumedang - Murah, Ramah, Amanah'
  site: 'https://example.com' # Nanti Cloudflare akan otomatis menyesuaikan
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: false 

# Default SEO metadata
metadata:
  title:
    default: 'Sedot WC Sumedang - Murah, Ramah, Amanah'
    template: '%s â€” Sedot WC SUMEDANG'
  description: "Tukang Sedot WC SUMEDANG profesional. Melayani sedot septic tank penuh, pelancaran saluran mampet, dan limbah industri. Respon cepat & harga transparan!"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'Sedot WC Sumedang - Murah, Ramah, Amanah'
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@sedotwc_kotaini'
    site: '@sedotwc_kotaini'
    cardType: summary_large_image

i18n:
  language: id
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' 
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' 
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'blog' 
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'blog' 
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null 

ui:
  theme: 'light' # Untuk jasa sedot WC, tema "Light" biasanya terlihat lebih bersih dan terpercaya

